config/routes.rb
Rails.application.routes.draw do
  root to: "links#index" # or new? can't decide...
  post '/', to: 'links#create'
  get ':token', to: 'links#external', as: :external, param: :token
  get ':token/info', to: 'links#show', as: :link, param: :token
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :visits

  validates :url, format: URI::regexp(%w(http https)), presence: true, uniqueness: true
  validates :token, presence: true, uniqueness: true
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :link

  validates :link_id, presence: true
  validates :ip, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
    @link = Link.new
  end

  def create
    @link = Link.find_or_initialize_by(link_params)
    @link.token = new_token unless Link.exists? @link.id

    if @link.save
      redirect_to link_path(@link.token)
    else
      flash[:alert] = @link.errors.full_messages
      redirect_to root_path
    end
  end

  def show
    @link = Link.find_by(token: params[:token])
  end

  def external
    @link = Link.find_by(token: params[:token])
    visit = @link.visits.new(ip: request.remote_ip)

    if visit.save
      redirect_to @link.url
    else
      flash[:alert] = visit.errors.full_messages
      redirect_to link_path(@link.token)
    end
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end

  def new_token
    loop do
      token = SecureRandom.urlsafe_base64(4)
      break token unless Link.find_by(token: token)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div><%= msg %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/links/index.html.erb
<h1>Shortener</h1>

<%= form_with model: @link, url: root_path do |form| %>
  <%= form.text_area :url %>
  <%= form.submit %>
<% end %>
</br>
Shortened url list:
<% @links.each do |l| %>
<p><%= link_to l.url, link_path(l.token) %></p>
<% end %>

app/views/links/show.html.erb
<%= link_to 'Home', root_path %>

<!-- <p>shorturl: <%= link_to external_url(@link.token), external_url(@link.token), data: { turbolinks: false } %></p> -->
<p>shorturl: <%= link_to external_url(@link.token), external_url(@link.token), method: :get %></p>
<p>shorturl visitor count: <%= @link.visits.size %></p>
<p>
  visitors:
  <% @link.visits.each do |v| %>
  <p>ip: "<%= v.ip %>"<% end %></p>
</p>